version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 730006451716.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd simple-api # Navigate into the correct directory
      - docker build -t simple-apidd:latest .
      - docker tag simple-apidd:latest 730006451716.dkr.ecr.ap-south-1.amazonaws.com/simple-apidd:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 730006451716.dkr.ecr.ap-south-1.amazonaws.com/simple-apidd:latest
