kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    clusterName: "wordsmith-cluster"
    registry: "public.ecr.aws/datadog"    
    tags:
      - "env:prod"
  features:
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            podSelector:
               matchLabels:
                 app: simple-api
            ddTraceVersions:
              java: "1"
    admissionController:
      enabled: true
      mutateUnlabelled: true 
    logCollection:
      enabled: true
      containerCollectAll: true
    usm:
      enabled: true
    npm:
      enabled: true
