apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        # This label is what Datadog will use to find and instrument this pod
        app: simple-api
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
      - name: api
        # IMPORTANT: Replace this with your ECR image path
        image: 730006451716.dkr.ecr.ap-south-1.amazonaws.com/simple-api:latest
        ports:
        - containerPort: 8080
        env:
          - name: DD_TRACE_AGENT_URL
            value: 'unix:///var/run/datadog/apm.socket'
        volumeMounts:
        - name: apmsocketpath
          mountPath: /var/run/datadog
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath    
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-service
spec:
  type: LoadBalancer
  selector:
    app: simple-api
  ports:
  - port: 80
    targetPort: 8080
